language: php
php:
  - 7.0
  - 7.1
before_script:
  - composer require nimut/testing-framework
  - composer require cobweb/svconnector_feed
script:
  - phpunit --colors -c vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/
  - >
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    phpunit --colors -c vendor/nimut/testing-framework/res/Configuration/FunctionalTests.xml Tests/Functional/;
